### ISSUE TITLE
Object type 'ns1:<>' is not supported

### ISSUE THREAD

**Issue by bneelon85** [kle043/komle#11]
I am trying to query data from a WITSML server using `StoreClient`.  I have validated that the url, credentials, and endpoints(wells, wellbores, etc) work by utilizing [PDS WITSMLstudio](https://github.com/pds-technology/witsml-studio).

I've adapted the example at the end of [hello_witsml.py](https://github.com/kle043/komle/blob/master/examples/hello_witsml.py):

```
import os
import pyxb
from komle.bindings.v1411.read import witsml
from komle.soap_client import StoreClient
from komle.uom_converter import conversion_factor, get_unit
from komle import utils as ku
import pandas as pd # Not included in komle setup.py
from lxml import etree


# This will fail if you don't have credentials to a witsml server
store_client = StoreClient(service_url='https://aaa.bbbbb.com/WMLS/WMLSService.svc',
                           username='xxxx@yyyyy.com',
                           password='someAwesomePassword')

id_logs = store_client.get_logs(witsml.obj_log())
print(id_logs)

wellbores = store_client.get_wellbores(witsml.obj_wellbore())
print(wellbores)
```

`id_logs` returns `komle.soap_client.StoreException: -101: Object type 'ns1:logs' is not supported.` 

and 

`wellbores` returns `komle.soap_client.StoreException: -101: Object type 'ns1:wellbores' is not supported.`

Again, I've validated via WITSMLstudio that both `logs` and `wellbores` are accessible with my URL and credentials.

Thanks for any help you can provide!

**Comment by bneelon85** [comment]
Actually just realized I'm querying a WITSML 1.3.1.1 server. I imagine that's the problem as this was built for Version 1.4.1.1 and 2. 

Is it not backwards compatible?

**Comment by kle043** [comment]
Hi, nope, you would need some bindings for v1.3.1.1 and probably a corresponding [WSDL](http://w3.energistics.org/schema/witsml_v1.3.1_api/WMLS.WSDL). The bindings can be generated, I added the script I used for the write bindings [generate.py](../blob/7a232bbe6c0d957025801939c143643404c16b9f/generate.py). So if you want to you can create your own bindings, you just needs to figure out where the xsd files are.

**Comment by bneelon85** [comment]
@kle043 thanks for your quick response! I will take a crack at generating the bindings for v1.3.1.1. Have a great one!
