### ISSUE TITLE
Unable to convert DOM node

### ISSUE THREAD

**Issue by jonnymaserati** [kle043/komle#5]
Hi there

I'm trying out your code to see if I can import some Volve data but I'm not able to read in a file without getting the following error:
```
Unable to convert DOM node {http://www.witsml.org/schemas/1series}priv_objectGrowing at <unknown>[1:4462] to binding
```
Some additional info:
```
Exception has occurred: UnrecognizedContentError
Invalid content priv_objectGrowing at <unknown>[1:4462] (expect {http://www.witsml.org/schemas/1series}itemState or {http://www.witsml.org/schemas/1series}serviceCategory or {http://www.witsml.org/schemas/1series}comments or {http://www.witsml.org/schemas/1series}acquisitionTimeZone or {http://www.witsml.org/schemas/1series}defaultDatum or {http://www.witsml.org/schemas/1series}privateGroupOnly or {http://www.witsml.org/schemas/1series}extensionAny or {http://www.witsml.org/schemas/1series}extensionNameValue)
  File "/tmp/build/80754af9/python_1573076469108/work/Modules/pyexpat.c", line 461, in EndElement
```
Looking a bit closer, it appears that there's a bunch of tags with a `priv_` prefix that are casing the issue. Is it possible to add a `try except` for `UnrecognizedContentError` if there's an unofficial tag and have these tags ignored?

**Comment by kle043** [comment]
Hi, it's a while since I looked at the schema, but would suspect that the `priv_` nodes are not part of witsml and placed somewhere where the schema says no to wildcard elements. 

Don't think I want to change the code to allow invalid documents, and it would be difficult since the bindings uses pyxb that does quite a good job in validating;)

But if you still think the bindings can be useful I guess it would just take a couple of lines of code to fix the document, something like
``` python
from komle.bindings.v1411.read import witsml
from lxml import etree

tree=etree.parse("MY_VOLVE_FILE_WITH_PRIV_NODE.xml")

for not_witsml in tree.xpath("//*[starts-with(name(), 'priv_')]"):
    not_witsml.getparent().remove(not_witsml)

logs = witsml.CreateFromDocument(etree.tostring(tree))
```

**Comment by jonnymaserati** [comment]
Yeah, I was thinking something similar, a pre-processing step to remove the offensive tags, but your suggested code is more elegant than what I would have come up with!

I don't think these tags are used, it looks like the operator has added them for internal use so I'm okay not processing them.

Thank you!

**Comment by kle043** [comment]
Vendors often add some private stuff, although they should have used the customData tag for that I suspect.

Thanks for the update on volve witsml:)
