### ISSUE TITLE
Filenames need updating

### ISSUE THREAD

**Issue by jonnymaserati** [kle043/komle#6]
Hell there

I was looking at the following example and in order to get it to run I need to update the filenames:
```
examples/hello_witsml2.py
```
It works if I point them at the filenames with a `(Case Conflict)` suffix.

Interestingly, it's loading `komle.bindings.v20` but the `.xml` files have a `<eml:Aliases authority="1.4.1.1">' property`

**Comment by kle043** [comment]
Hi, the `hello_witsml2.py` file is an example using witsml version 2.0(schemaVersion="2.0" in the file), and should not work for xml files following other standards. Some of the files in the sample directory follows version 1.4.1.1, and you have to use the 1.4.1.1 bindings in a separate runtime to work with them.

**Comment by jonnymaserati** [comment]
Hi there

Understood, my point was more that the code references filenames that does't exist.

https://github.com/kle043/komle/blob/d598ecba841b3b0aa243ffa6fb9ac59f86aaeba3/examples/hello_witsml2.py#L20

https://github.com/kle043/komle/blob/d598ecba841b3b0aa243ffa6fb9ac59f86aaeba3/examples/hello_witsml2.py#L39

I think you changed the name of the file and didn't update the example? It's just nice to have an example that works when you run it?

**Comment by kle043** [comment]
Guess I should have called it traj_file instead of mud_file, but the files seems to be there 
https://github.com/kle043/komle/blob/d598ecba841b3b0aa243ffa6fb9ac59f86aaeba3/tests/samples/Trajectory.xml#L1
and
https://github.com/kle043/komle/blob/d598ecba841b3b0aa243ffa6fb9ac59f86aaeba3/tests/samples/Log.xml#L1

**Comment by jonnymaserati** [comment]
Oh, that's strange... maybe it's an issue with my local repo?

![image](https://user-images.githubusercontent.com/41046859/108063783-09e16280-705c-11eb-82df-0da1d88da039.png)

**Comment by kle043** [comment]
Yeap, would think so, good luck with the volve data:)
